### ISSUE TITLE
Todo list for the first release.

### ISSUE THREAD

**Issue by offnaria** [archlab-tokyotech/rv-pc#1]
- [ ] Port for newer versions of Vivado (2023.2, 2024.1, ...)
- [ ] Update diskimage generation (if needed).
- [ ] Create a testbench for the simulation.

**Comment by offnaria** [comment]
Additionally, this should be done:
- [ ] Change the name of the processor core appropriately.
